name = "iq"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[vars]
TELEGRAM_BOT_TOKEN = "7963022767:AAHjFxSvn16CK2BBWX1aEE_3kBX7u1ZM57c"


[[kv_namespaces]]
binding = "KV_IQMASTER"
id = "fce3c2c52c3d4e9ba9109c5195f0547c"
preview_id = "fce3c2c52c3d4e9ba9109c5195f0547c"

[ai]
binding = "AI"
