name = "iq"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[vars]
# Public variables (can be set here)

[[kv_namespaces]]
binding = "KV"
id = "fce3c2c52c3d4e9ba9109c5195f0547c"
preview_id = "fce3c2c52c3d4e9ba9109c5195f0547c"

[ai]
binding = "AI"
